### ISSUE TITLE
API (Trưởng bộ môn): Phân giảng

### ISSUE THREAD

**Issue by spicy-tomato** [pthai-it-dev/education-supporting-system#3]
- [x] ~~GET: Lấy danh sách lịch dạy trong học kỳ~~ Dùng API lấy danh sách lớp học phần của bộ môn
- [x] ~~GET: Lấy danh sách lịch dạy CHƯA ĐƯỢC PHÂN trong học kỳ~~
- [x] POST: Cập nhật phân giảng
- [x] ? GET: Lấy danh sách lịch dạy bị trùng

**Comment by just-pthai-it** [comment]
Done
